<?php



//drupal_add_css(drupal_get_path('module', 'portfolio_fields') . '/custom.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));

drupal_add_js(drupal_get_path('module', 'portfolio_fields') . '/image.js', array('group' => JS_THEME, 'every_page' => TRUE));


$fonts = array(
  '#tag' => 'link', // The #tag is the html tag - <link />
  '#attributes' => array( // Set up an array of attributes inside the tag
    'href' => 'http://fonts.googleapis.com/css?family=Fanwood+Text', 
    'rel' => 'stylesheet',
    'type' => 'text/css',
  ),
);
drupal_add_html_head($fonts, 'google_font_fanwood_text');




function portfolio_fields_menu_link(array $variables) {
  $element = $variables['element'];
  $sub_menu = '';
  $element['#localized_options']['html'] = TRUE;


  if ($element['#below']) {
    $sub_menu = drupal_render($element['#below']);
  }
  
  if ($element['#original_link']['menu_name'] == "main-menu"){

    $element['#title'] .= '<span class="description">'.$element['#localized_options']['attributes']['title'].'</span>';
    }
  
  $output = l($element['#title'], $element['#href'], $element['#localized_options']);
  return '<li' . drupal_attributes($element['#attributes']) . '>' . $output . $sub_menu . "</li>\n";
}




$viewport = array(
    '#tag' => 'meta', // The #tag is the html tag - <link />
    '#attributes' => array( // Set up an array of attributes inside the tag
	'name' => 'viewport',
	'content' => 'width=device-width, initial-scale=1.0, maximum-scale=1.0'
    ),
);
drupal_add_html_head($viewport, 'viewport');

$favicon = array(
    '#tag' => 'link', // The #tag is the html tag - <link />
    '#attributes' => array( // Set up an array of attributes inside the tag
	'rel' => 'shortcut icon',
	'href' => '/sites/default/files/favicon.ico',
	'type' => 'image/vnd.microsoft.icon'
    ),
);
drupal_add_html_head($favicon, 'favicon');

/*
$element = array(
  '#tag' => 'script', // The #tag is the html tag - <link />
  '#prefix' => '<!--[if IE]>',
  '#attributes' => array( // Set up an array of attributes inside the tag
    // ... 
  ),
  '#suffix' => '<![endif]-->';
);
drupal_add_html_head($element, 'my_key');
*/



